// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCHt3I7fZHHabXNK7YylpmTd9gAvTCHek',
    appId: '1:604490950881:web:003df59dc54242a20fafa0',
    messagingSenderId: '604490950881',
    projectId: 'slvh-b707f',
    authDomain: 'slvh-b707f.firebaseapp.com',
    storageBucket: 'slvh-b707f.firebasestorage.app',
    measurementId: 'G-D7DKHYQXND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKTK_f31H4XD755wpoxk_8Njh0bMsLD_c',
    appId: '1:604490950881:android:c6b370ac62808d3d0fafa0',
    messagingSenderId: '604490950881',
    projectId: 'slvh-b707f',
    storageBucket: 'slvh-b707f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbh6BLrE1y0TMVqTASJEI9htSs2iDioZA',
    appId: '1:604490950881:ios:870a8aa397f791d10fafa0',
    messagingSenderId: '604490950881',
    projectId: 'slvh-b707f',
    storageBucket: 'slvh-b707f.firebasestorage.app',
    iosBundleId: 'com.example.slvhApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbh6BLrE1y0TMVqTASJEI9htSs2iDioZA',
    appId: '1:604490950881:ios:870a8aa397f791d10fafa0',
    messagingSenderId: '604490950881',
    projectId: 'slvh-b707f',
    storageBucket: 'slvh-b707f.firebasestorage.app',
    iosBundleId: 'com.example.slvhApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCHt3I7fZHHabXNK7YylpmTd9gAvTCHek',
    appId: '1:604490950881:web:0d5553fac6484eab0fafa0',
    messagingSenderId: '604490950881',
    projectId: 'slvh-b707f',
    authDomain: 'slvh-b707f.firebaseapp.com',
    storageBucket: 'slvh-b707f.firebasestorage.app',
    measurementId: 'G-85SZFV3L9V',
  );
}
