import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:provider/provider.dart';
import 'package:slvh_app/features/cart/providers/cart_provider.dart';
import 'package:slvh_app/features/orders/models/order_model.dart';
import 'package:slvh_app/features/orders/services/order_service.dart';
import 'package:slvh_app/features/payments/screens/payment_screen.dart';
import 'package:slvh_app/features/pickup_slots/models/slot_model.dart';
import 'package:slvh_app/features/pickup_slots/screens/slot_picker_screen.dart';

/// Checkout screen orchestrates the full order creation flow
/// Flow: Cart → Slot Selection → Order Creation → Payment
class CheckoutScreen extends StatefulWidget {
  final Map<String, dynamic> cartSummary;

  const CheckoutScreen({
    Key? key,
    required this.cartSummary,
  }) : super(key: key);

  @override
  State<CheckoutScreen> createState() => _CheckoutScreenState();
}

class _CheckoutScreenState extends State<CheckoutScreen> {
  final OrderService _orderService = OrderService();

  DateTime? _selectedPickupDate;
  PickupSlotModel? _selectedPickupSlot;
  bool _isCreatingOrder = false;
  String? _errorMessage;

  /// Step 1: Show slot picker
  Future<void> _selectPickupSlot() async {
    final result = await Navigator.push(
      context,
      MaterialPageRoute(builder: (_) => const SlotPickerScreen()),
    );

    if (result != null && mounted) {
      final selectedDate = result['date'] as DateTime;
      final selectedSlot = result['slot'] as PickupSlotModel;

      setState(() {
        _selectedPickupDate = selectedDate;
        _selectedPickupSlot = selectedSlot;
        _errorMessage = null;
      });
    }
  }

  /// Step 2: Create order and proceed to payment
  Future<void> _proceedToPayment() async {
    if (_selectedPickupDate == null || _selectedPickupSlot == null) {
      setState(() => _errorMessage = 'Please select a pickup slot');
      return;
    }

    try {
      setState(() => _isCreatingOrder = true);

      // Get current user
      final currentUser = FirebaseAuth.instance.currentUser;
      if (currentUser == null) {
        throw Exception('User not authenticated');
      }

      // Build order items from cart
      final cartItems = widget.cartSummary['items'] as List<dynamic>? ?? [];
      final orderItems = cartItems.map((item) {
        return OrderItem(
          productId: item['productId'] as String,
          productName: item['productName'] as String,
          quantity: item['quantity'] as int,
          unitPrice: (item['unitPrice'] as num).toDouble(),
          totalPrice: (item['totalPrice'] as num).toDouble(),
          selectedTierUnit: item['selectedTierUnit'] as String?,
          discountPercent: item['discountPercent'] as double?,
        );
      }).toList();

      // Create order model
      final order = OrderModel(
        id: 'temp',  // Will be generated by Firestore
        customerId: currentUser.phoneNumber ?? '',
        items: orderItems,
        subtotal: (widget.cartSummary['subtotal'] as num).toDouble(),
        tax: (widget.cartSummary['estimatedTax'] as num).toDouble(),
        total: (widget.cartSummary['total'] as num).toDouble(),
        status: OrderStatus.pendingPayment,
        paymentId: null,
        paymentStatus: null,
        pickupDate: _selectedPickupDate!.toString().split(' ')[0], // YYYY-MM-DD
        pickupTime: _selectedPickupSlot!.getDisplayTime(),
        pickupSlotId: _selectedPickupSlot!.id,
        createdAt: DateTime.now(),
      );

      // Create order with atomic batch write (reduces stock)
      final orderId = await _orderService.createOrder(order: order);

      if (!mounted) return;

      // Clear cart after successful order creation
      final cartProvider = context.read<CartProvider>();
      cartProvider.clearCart();

      // Navigate to payment screen
      if (mounted) {
        Navigator.push(
          context,
          MaterialPageRoute(
            builder: (_) => PaymentScreen(
              orderId: orderId,
              amount: order.total,
              customerPhone: currentUser.phoneNumber ?? '',
              cartSummary: widget.cartSummary,
              orderModel: order.copyWith(id: orderId),
            ),
          ),
        ).then((paymentResult) {
          // After payment screen closes
          if (paymentResult != null && mounted) {
            if (paymentResult['status'] == 'Payment Verification Pending') {
              // Payment screenshot was uploaded successfully
              // Navigate to order summary
              context.push('/order-summary', extra: order.copyWith(id: orderId));
            } else if (paymentResult['status'] == 'Payment Retry Pending') {
              // Payment succeeded but upload failed - order saved for retry
              ScaffoldMessenger.of(context).showSnackBar(
                SnackBar(
                  content: Text(paymentResult['message'] ?? 
                      'Your order is saved. Retry anytime.'),
                  backgroundColor: Colors.blue,
                  duration: const Duration(seconds: 4),
                ),
              );
              context.pop();
            }
          }
        });
      }
    } catch (e) {
      setState(() {
        _errorMessage = 'Failed to create order: $e';
        _isCreatingOrder = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Checkout'),
        centerTitle: true,
        elevation: 0,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Order summary
            _buildOrderSummaryCard(),
            const SizedBox(height: 20),

            // Pickup slot selection
            _buildPickupSlotCard(),
            const SizedBox(height: 20),

            // Error message
            if (_errorMessage != null) ...[
              Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  color: Colors.red[50],
                  borderRadius: BorderRadius.circular(8),
                  border: Border.all(color: Colors.red[300]!),
                ),
                child: Row(
                  children: [
                    Icon(Icons.error_outline, color: Colors.red),
                    const SizedBox(width: 12),
                    Expanded(
                      child: Text(
                        _errorMessage!,
                        style: TextStyle(color: Colors.red[700]),
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 20),
            ],

            // Action buttons
            _buildActionButtons(),
            const SizedBox(height: 24),
          ],
        ),
      ),
    );
  }

  /// Build order summary card
  Widget _buildOrderSummaryCard() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.grey[300]!),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.05),
            blurRadius: 8,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'Order Summary',
            style: Theme.of(context).textTheme.titleMedium?.copyWith(
                  fontWeight: FontWeight.bold,
                ),
          ),
          const SizedBox(height: 12),
          _SummaryRow(
            label: 'Items',
            value: '${widget.cartSummary['itemCount']}',
          ),
          const SizedBox(height: 8),
          _SummaryRow(
            label: 'Subtotal',
            value:
                '₹${(widget.cartSummary['subtotal'] as num).toStringAsFixed(2)}',
          ),
          const SizedBox(height: 8),
          _SummaryRow(
            label: 'Tax (5%)',
            value:
                '₹${(widget.cartSummary['estimatedTax'] as num).toStringAsFixed(2)}',
          ),
          const SizedBox(height: 12),
          Divider(color: Colors.grey[300]),
          const SizedBox(height: 12),
          _SummaryRow(
            label: 'Total',
            value: '₹${(widget.cartSummary['total'] as num).toStringAsFixed(2)}',
            isTotal: true,
          ),
        ],
      ),
    );
  }

  /// Build pickup slot selection card
  Widget _buildPickupSlotCard() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: _selectedPickupSlot != null ? Colors.green[50] : Colors.blue[50],
        borderRadius: BorderRadius.circular(12),
        border: Border.all(
          color: _selectedPickupSlot != null
              ? Colors.green[300]!
              : Colors.blue[200]!,
        ),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Icon(
                Icons.access_time,
                color: _selectedPickupSlot != null
                    ? Colors.green[700]
                    : Colors.blue[700],
                size: 24,
              ),
              const SizedBox(width: 12),
              Text(
                'Pickup Slot',
                style: TextStyle(
                  fontSize: 14,
                  fontWeight: FontWeight.bold,
                  color: _selectedPickupSlot != null
                      ? Colors.green[700]
                      : Colors.blue[700],
                ),
              ),
            ],
          ),
          const SizedBox(height: 12),
          if (_selectedPickupSlot != null) ...[
            Row(
              children: [
                Icon(
                  Icons.check_circle,
                  color: Colors.green[700],
                  size: 20,
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Date: $_selectedPickupDate',
                        style: const TextStyle(
                          fontWeight: FontWeight.bold,
                          fontSize: 13,
                        ),
                      ),
                      const SizedBox(height: 4),
                      Text(
                        'Time: ${_selectedPickupSlot!.getDisplayTime()}',
                        style: const TextStyle(fontSize: 13),
                      ),
                    ],
                  ),
                ),
              ],
            ),
            const SizedBox(height: 12),
            SizedBox(
              width: double.infinity,
              child: OutlinedButton.icon(
                onPressed: _isCreatingOrder ? null : _selectPickupSlot,
                icon: const Icon(Icons.edit),
                label: const Text('Change Slot'),
              ),
            ),
          ] else ...[
            Text(
              'Select a pickup date and time',
              style: TextStyle(color: Colors.grey[700], fontSize: 13),
            ),
            const SizedBox(height: 12),
            SizedBox(
              width: double.infinity,
              child: ElevatedButton.icon(
                onPressed: _isCreatingOrder ? null : _selectPickupSlot,
                icon: const Icon(Icons.calendar_today),
                label: const Text('Select Pickup Time'),
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.blue[700],
                  foregroundColor: Colors.white,
                ),
              ),
            ),
          ],
        ],
      ),
    );
  }

  /// Build action buttons
  Widget _buildActionButtons() {
    return Column(
      children: [
        SizedBox(
          width: double.infinity,
          height: 48,
          child: ElevatedButton.icon(
            onPressed: _isCreatingOrder || _selectedPickupSlot == null
                ? null
                : _proceedToPayment,
            icon: _isCreatingOrder
                ? SizedBox(
                    width: 20,
                    height: 20,
                    child: CircularProgressIndicator(
                      strokeWidth: 2,
                      valueColor: AlwaysStoppedAnimation(Colors.white),
                    ),
                  )
                : const Icon(Icons.payment),
            label: Text(_isCreatingOrder ? 'Creating Order...' : 'Proceed to Payment'),
            style: ElevatedButton.styleFrom(
              backgroundColor: Colors.orange[700],
              foregroundColor: Colors.white,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(8),
              ),
            ),
          ),
        ),
        const SizedBox(height: 12),
        SizedBox(
          width: double.infinity,
          height: 48,
          child: OutlinedButton.icon(
            onPressed: _isCreatingOrder ? null : () => Navigator.pop(context),
            icon: const Icon(Icons.arrow_back),
            label: const Text('Back to Cart'),
            style: OutlinedButton.styleFrom(
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(8),
              ),
            ),
          ),
        ),
      ],
    );
  }
}

/// Summary row helper widget
class _SummaryRow extends StatelessWidget {
  final String label;
  final String value;
  final bool isTotal;

  const _SummaryRow({
    required this.label,
    required this.value,
    this.isTotal = false,
  });

  @override
  Widget build(BuildContext context) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(
          label,
          style: TextStyle(
            fontSize: isTotal ? 14 : 12,
            fontWeight: isTotal ? FontWeight.bold : FontWeight.w500,
            color: isTotal ? Colors.black87 : Colors.grey[700],
          ),
        ),
        Text(
          value,
          style: TextStyle(
            fontSize: isTotal ? 14 : 12,
            fontWeight: isTotal ? FontWeight.bold : FontWeight.w600,
            color: isTotal ? Colors.orange[700] : Colors.black87,
          ),
        ),
      ],
    );
  }
}
